# Generated by Django 4.1.7 on 2023-03-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0011_student_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Feedback',
            new_name='Student_Notification',
        ),
    ]
