# Generated by Django 4.1.7 on 2023-04-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0020_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.TextField()),
                ('notes', models.FileField(upload_to='media/lesson_note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyApp.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyApp.subject')),
            ],
        ),
    ]
