# Generated by Django 4.1.7 on 2023-04-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0021_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='staff',
        ),
    ]
