# Generated by Django 4.1.7 on 2023-04-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0022_remove_lesson_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
