# Generated by Django 4.1.7 on 2023-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0029_remove_lesson_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment',
            field=models.FileField(blank=True, null=True, upload_to='media/lesson_assignment'),
        ),
    ]
