# Generated by Django 4.1.7 on 2023-04-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0030_lesson_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='media/lesson_note'),
        ),
    ]
