# Generated by Django 4.1.7 on 2023-04-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0033_rename_feedback_student_submission_submission_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Submission',
        ),
    ]
