# Generated by Django 4.1.7 on 2023-04-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0034_delete_student_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
    ]
