# Generated by Django 4.1.7 on 2023-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0036_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
