# Generated by Django 4.1.7 on 2023-05-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0037_submission_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_status',
        ),
    ]
