# Generated by Django 4.1.7 on 2023-05-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0038_remove_submission_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
