# Generated by Django 4.1.7 on 2023-05-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0040_alter_submission_submission_file_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='description',
            new_name='content',
        ),
    ]
