# Generated by Django 4.1.7 on 2023-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0041_rename_description_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
